version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
